```{r init, echo=FALSE}
library("ggplot2")
library("RCurl")
library("plyr")
library("scales")

readRenviron("~/.Renviron") # Make sure you have a APPMETRICS_CREDENTIALS=username:password entry
metrics_credentials <- Sys.getenv(c("APPMETRICS_CREDENTIALS"))
```

```{r vars, echo=FALSE}
startTime <- "2012-09-05 00:00:00"
endTime <- "2013-01-14 00:00:00"
```

```{r fetchData, echo=FALSE}
application <- "CIAPILatencyCollector.AllServiceMonitor.BuiltIn" #will switch to CIAPILatencyCollector once https://github.com/fandrei/AppMetrics/issues/101 has been resolved
data_url <- URLencode(paste("http://metrics.cityindex.com/GetRecords.ashx?Application=",application,"&StartTime=",startTime,'&EndTime=',endTime, sep = ''))

webpage2 <- getURL(data_url,userpwd=metrics_credentials, httpauth = 1L)
logdata2 <- read.table(tc <- textConnection(webpage2), header=F, sep="\t", fill=TRUE, as.is=c(1,4)); 
close(tc)
colnames(logdata2)=c('session','timestamp','key','value')
```

```{r convert_to_CIAPILatencyCollector_names, echo=FALSE}
logdata2bak <- logdata2

# Temporary measure to convert CIAPILatencyCollector.AllServiceMonitor.BuiltIn names to CIAPILatencyCollector names.  Will not be needed once https://github.com/fandrei/AppMetrics/issues/101 has been resolved
logdata2$key <- sub('Latency CIAPI\\..*', '', logdata2$key, perl = TRUE)
logdata2 <- subset(logdata2, key != '')

logdata2$key <- sub('Latency https://ciapi.cityindex.com/TradingApi/', 'Latency CIAPI.',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.session/deleteSession.*', 'Latency CIAPI.LogOut',logdata2$key, perl = TRUE)
logdata2$key <- sub('Latency CIAPI.session', 'Latency CIAPI.LogIn',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.spread/markets?MarketName=&MarketCode=&ClientAccountId=400194351&MaxResults=100&UseMobileShortName=False', 'Latency CIAPI.ListSpreadMarkets',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.useraccount/ClientAndTradingAccount', 'Latency CIAPI.GetClientAndTradingAccount',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.useraccount/UserAccount/ClientAndTradingAccount', 'Latency CIAPI.GetClientAndTradingAccount',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.market/400616150/information', 'Latency CIAPI.GetMarketInformation',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.market/400616150/barhistory?interval=MINUTE&span=1&PriceBars=20', 'Latency CIAPI.GetPriceBars',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.order/openpositions?.*', 'Latency CIAPI.ListOpenPositions',logdata2$key, perl = TRUE)
logdata2$key <- sub('Latency CIAPI.order/order/openpositions?.*', 'Latency CIAPI.ListOpenPositions',logdata2$key, perl = TRUE)
logdata2$key <- sub('Latency CIAPI.news/dj/UK?MaxResults=10', 'Latency CIAPI.ListNewsHeadlinesWithSource',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.order/order/tradehistory?TradingAccountId=400290710&MaxResults=20', 'Latency CIAPI.ListTradeHistory',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.order/newtradeorder', 'Latency CIAPI.Trade',logdata2$key, fixed = TRUE)
logdata2$key <- sub('Latency CIAPI.message/.*', 'Latency CIAPI.LookupMessage',logdata2$key, perl = TRUE)

uniqueFunctions <-  unique(logdata2$key)
```

```{r groupSessionByNodes, echo=FALSE}
nodes2 <- logdata2[logdata2$"key" %in% c("ClientIP"), ]

nodes2$nodeName = nodes2$value
nodes2$nodeName <- sub('46.137.47.103', 'AWS-EU-WEST-1B-79.125.25.36', nodes2$nodeName, fixed = TRUE)
nodes2$nodeName <- sub('79.125.25.36', 'AWS-EU-WEST-1B-79.125.25.36', nodes2$nodeName, fixed = TRUE)

nodes2$nodeName <- sub('AWS-EU-WEST-1B-AWS-EU-WEST-1B-79.125.25.36', 'AWS-EU-WEST-1B-79.125.25.36', nodes2$nodeName, fixed = TRUE)

nodes2 <- subset(nodes2, select=c(-timestamp,-key,-value))
```


Latency between different services
-----------------------------------
  The following graph compares the latency of different services for the same node:
```{r service_latency_plot, fig.width=10, fig.height = 7, tidy=FALSE, warning=FALSE}
rpc2 <- logdata2[logdata2$"key" %in% c("Latency CIAPI.LogIn"
                                     ,"Latency CIAPI.LogOut"
                                     ,"Latency CIAPI.ListSpreadMarkets"
                                     ,"Latency CIAPI.GetClientAndTradingAccount"     
                                     ,"Latency CIAPI.GetMarketInformation"
                                     ,"Latency CIAPI.GetPriceBars"
                                     ,"Latency CIAPI.ListOpenPositions"
                                     ,"Latency CIAPI.ListNewsHeadlinesWithSource"
                                     ,"Latency CIAPI.ListTradeHistory"
                                     ,"Latency CIAPI.Trade" ), ]

rpc2$datetime <- strptime(rpc2$timestamp, "%Y-%m-%d %H:%M:%S")
rpc2$key <- sub('Latency CIAPI.', '',rpc2$key)
rpc2 <- join(rpc2, nodes2, by = "session", match = "first")
rpc2 <- rpc2[rpc2$nodeName %in% c("AWS-EU-WEST-1B-79.125.25.36"),]

d <- ggplot(rpc2, aes(x=datetime, y=as.double(value)))
d <- d + ylab("Latency in seconds") + xlab("Measurement time (UTC)")
d <- d + scale_y_log10(breaks=c(0.1,0.3,0.6), limits=c(0.05, 0.7))
d <- d + geom_hex()
d <- d + stat_quantile( quantiles = c(0.5, 0.98) ) 
d <- d + geom_rug(aes(x=NULL, y=as.double(value)), col=rgb(.5,0,0, alpha=.05))
d <- d + scale_fill_gradient(low="grey", high="red") + theme_bw()
d <- d + facet_grid(key ~ nodeName)
d <- d + opts(strip.text.y = theme_text( angle=0))
print(d)
```
Performance has been consistenly good over the past week, with a slight degredation in performance for the ListTradeHistory service between 27th Sept and 29th Sept

Selective latencies in depth
-----------------------------------
  The following graph compares:
  
  1. Login - A simple "change server state" query
1. ListTradeHistory - A complex "readonly" query
1. Trade - A complex "change server state" query

```{r service_latency_plot_in_depth, fig.width=10, fig.height = 7, tidy=FALSE, warning=FALSE}
rpc3 <- logdata2[logdata2$"key" %in% c("Latency CIAPI.LogIn","Latency CIAPI.LogOut","Latency CIAPI.Trade"), ]

rpc3$datetime <- strptime(rpc3$timestamp, "%Y-%m-%d %H:%M:%S")
rpc3$key <- sub('Latency CIAPI.', '',rpc3$key)
rpc3 <- join(rpc3, nodes2, by = "session", match = "first")
rpc3 <- rpc3[rpc3$nodeName %in% c("AWS-EU-WEST-1B-79.125.25.36"),]

d <- ggplot(rpc3, aes(x=datetime, y=as.double(value)))
d <- d + ylab("Latency in seconds") + xlab("Measurement time (UTC)")
d <- d + scale_y_log10() 
d <- d + geom_hex()
d <- d + stat_quantile( quantiles = c(0.5, 0.98) ) 
d <- d + geom_rug(aes(x=NULL, y=as.double(value)), col=rgb(.5,0,0, alpha=.05))
d <- d + scale_fill_gradient(low="grey", high="red") + theme_bw()
d <- d + facet_grid(key ~ nodeName, scales="free_y")
d <- d + opts(strip.text.y = theme_text( angle=0))
print(d)
```

```{r service_login_histogram, fig.width=10, fig.height = 7, tidy=FALSE, warning=FALSE}
rpc4 <- logdata2[logdata2$"key" %in% c("Latency CIAPI.LogIn"), ]

rpc4$datetime <- strptime(rpc4$timestamp, "%Y-%m-%d %H:%M:%S")
rpc4$key <- sub('Latency CIAPI.', '',rpc4$key)

values4 <- as.numeric(rpc4$value)
values4 <- values4[values4 > 0]
hist(values4, br=200000, xlim = c(0,0.5), main="Login latency histogram", xlab="Latency")
```

```{r service_trade_histogram, fig.width=10, fig.height = 7, tidy=FALSE, warning=FALSE}
rpc5 <- logdata2[logdata2$"key" %in% c("Latency CIAPI.Trade"), ]

rpc5$datetime <- strptime(rpc5$timestamp, "%Y-%m-%d %H:%M:%S")
rpc5$key <- sub('Latency CIAPI.', '',rpc5$key)

values5 <- as.numeric(rpc5$value)
values5 <- values5[values5 > 0]
hist(values5, br=100000, xlim = c(0,0.5), main="Trade latency histogram",  xlab="Latency")
```

```{r service_login_histogram_2, fig.width=10, fig.height = 7, tidy=FALSE, warning=FALSE}
rpc4_1 <- logdata2[logdata2$"key" %in% c("Latency CIAPI.LogIn"), ]
rpc4_1 <- subset(rpc4_1, rpc4_1$value >= 0.5)

rpc4_1$datetime <- strptime(rpc4_1$timestamp, "%Y-%m-%d %H:%M:%S")
rpc4_1$key <- sub('Latency CIAPI.', '',rpc4_1$key)

values4_1 <- as.numeric(rpc4_1$value)
hist(values4_1, br=1000000, xlim = c(0.5,max(values4_1)), main="Login latency histogram", xlab="Latency")
```

```{r service_trade_histogram_2, fig.width=10, fig.height = 7, tidy=FALSE, warning=FALSE}
rpc5_1 <- logdata2[logdata2$"key" %in% c("Latency CIAPI.Trade"), ]
rpc5_1 <- subset(rpc5_1, rpc5_1$value >= 0.5)

rpc5_1$datetime <- strptime(rpc5_1$timestamp, "%Y-%m-%d %H:%M:%S")
rpc5_1$key <- sub('Latency CIAPI.', '',rpc5_1$key)

values5_1 <- as.numeric(rpc5_1$value)
values5_1 <- values5_1[values5_1 > 0]
hist(values5_1, br=100000, xlim = c(0.5,max(values5_1)), main="Trade latency histogram",  xlab="Latency")
```

```{r service_outstanding_values_count}
rpc6 <- logdata2[logdata2$"key" %in% c("Latency CIAPI.LogIn"
                                     ,"Latency CIAPI.LogOut"
                                     ,"Latency CIAPI.ListSpreadMarkets"
                                     ,"Latency CIAPI.GetClientAndTradingAccount"     
                                     ,"Latency CIAPI.GetMarketInformation"
                                     ,"Latency CIAPI.GetPriceBars"
                                     ,"Latency CIAPI.ListOpenPositions"
                                     ,"Latency CIAPI.ListNewsHeadlinesWithSource"
                                     ,"Latency CIAPI.ListTradeHistory"
                                     ,"Latency CIAPI.Trade" ), ]
rpc6$key <- sub('Latency CIAPI.', '',rpc6$key)

totalCounts <- aggregate(rpc6$value, by=list(rpc6$key), FUN=length)
rpc6 <- subset(rpc6, rpc6$value >= 1)

counts <- aggregate(rpc6$value, by=list(rpc6$key), FUN=length)
colnames(counts)[1] <- "Service name"
colnames(counts)[2] <- "Count"

counts$Percentage <- (counts$Count / totalCounts$x) * 100
```