CIAPI client side latency - 13 June 2012
===========================================
```{r init, echo=FALSE}
library("ggplot2")
library("RCurl")
library("plyr")
library("scales")
metrics_credentials <- Sys.getenv(c("APPMETRICS_CREDENTIALS"))
startTime <- "2012-07-03 13:00:00"
endTime <- "2012-07-03 14:00:00"
data_url <- URLencode(paste("http://metrics.labs.cityindex.com/GetRecords.ashx?Application=CIAPILatencyCollector&StartTime=",startTime,'&EndTime=',endTime, sep = ''))
```

```{r fetchData, echo=FALSE}
webpage <- getURL(data_url,userpwd=metrics_credentials, httpauth = 1L)
logdata <- read.table(tc <- textConnection(webpage), header=F, sep="\t", fill=TRUE, as.is=c(1,4)); 
close(tc)
colnames(logdata)=c('session','timestamp','key','value')
```

```{r groupSessionByNodes, echo=FALSE}
nodes <- logdata[logdata$"key" %in% c("ClientIP"), ]
nodes$nodeName = nodes$value
nodes <- subset(nodes, select=c(-timestamp,-key,-value))
```
Latency between different endpoints
-----------------------------------
The following chart compares the latency of the Default IIS page from different 
endpoints:
```{r network_latency_plot, fig.width=10, fig.height = 7, tidy=FALSE}
rpc <- logdata[logdata$"key" %in% c("Latency General.DefaultPage"), ]
rpc$datetime <- strptime(rpc$timestamp, "%Y-%m-%d %H:%M:%S")
rpc <- join(rpc, nodes, by = "session", match = "first")

d <- ggplot(rpc, aes(x=datetime, y=as.double(value)))
d <- d + scale_y_log10()
d <- d + geom_hex()
d <- d + scale_fill_gradient(low="grey", high="red") + theme_bw()
d <- d + facet_grid(nodeName ~ key)
print(d)
```
As is expected, latency is higher for nodes geographically further away.

Latency between different services
-----------------------------------
The following graph compares the latency of different services for the same node:
```{r service_latency_plot, fig.width=10, fig.height = 7, tidy=FALSE}
rpc2 <- logdata[logdata$"key" %in% c("Latency General.DefaultPage"
                                    ,"Latency CIAPI.LogIn"
                                    ,"Latency CIAPI.LogOut"
                                    ,"Latency CIAPI.ListCfdMarkets"
                                    ,"Latency CIAPI.GetClientAndTradingAccount"     
                                    ,"Latency CIAPI.GetMarketInformation"
                                    ,"Latency CIAPI.ListCfdMarkets"
                                    ,"Latency CIAPI.GetPriceBars"
                                    ,"Latency CIAPI.ListOpenPositions"
                                    ,"Latency CIAPI.ListNewsHeadlinesWithSource"
                                    ,"Latency CIAPI.ListTradeHistory"
                                    ,"Latency CIAPI.Trade" ), ]
rpc2$datetime <- strptime(rpc2$timestamp, "%Y-%m-%d %H:%M:%S")
rpc2$key <- sub('Latency CIAPI.', '',rpc2$key)
rpc2 <- join(rpc2, nodes, by = "session", match = "first")
rpc2 <- rpc2[rpc2$nodeName %in% c("46.137.187.155"),]

d <- ggplot(rpc2, aes(x=datetime, y=as.double(value)))
d <- d + ylab("Latency in seconds") + xlab("Measurement time (UTC)")
d <- d + scale_y_continuous(limits=c(0,1))
d <- d + geom_hex()
d <- d + scale_fill_gradient(low="grey", high="red") + theme_bw()
d <- d + facet_grid(key ~ nodeName, margins = c("key"))
d <- d + opts(strip.text.y = theme_text( angle=0))
print(d)
```
As can be seen, blah blah blah